### ISSUE TITLE
Build error on Windows machine.

### ISSUE THREAD

**Issue by jiapengjp** [koding/kite#102]
I've failed to install kite on Windows because SIGUSR2 doesn't exist.
Maybe there is no easy fix.
```
C:\go>go get github.com/koding/kite
# github.com/koding/kite
src\github.com\koding\kite\logger.go:105: undefined: syscall.SIGUSR2
```

**Comment by fatih** [comment]
Hi @jiapengjp 

Currently there is no Windows support for Kite. Only Mac OS X and Linux are supported. Though supporting would be easy, we just need some time to dig and fix the necessary problems.
