### ISSUE TITLE
Error : invalid operation: token.Cliams["kontrolKey"] (type) jwt.Claims does not support indexing

### ISSUE THREAD

**Issue by mrgleam** [koding/kite#163]
I use command $ go get in my project.

Error ->

`../github.com/koding/kite/kitekey/kitekey.go:105: invalid operation: token.Claims["kontrolKey"] (type jwt.Claims does not support indexing)`

**Comment by cihangir** [comment]
please see https://github.com/koding/kite/pull/161#issuecomment-226711805
