### ISSUE TITLE
kite.go:174:22: multiple-value uuid.NewV4() in single-value context

### ISSUE THREAD

**Issue by lukaasp** [koding/kite#216]
After running `go get github.com/koding/kite` I got response:

`# github.com/koding/kite
../../go/src/github.com/koding/kite/kite.go:174:22: multiple-value uuid.NewV4() in single-value context`

Same response when trying to run any of examples.

go version: go1.9.2 darwin/amd64
system: High Sierra

**Comment by cihangir** [comment]
hi @lukaasp 

That happens due to the uuid package's latest master has breaking changes, we recently switched using to `dep` tool. You can get our latest changes with the following commands

```
➜  /tmp cd /tmp
➜  /tmp echo $GOPATH
/tmp
➜  /tmp rm -rf ./src
➜  /tmp rm -rf ./pkg
➜  /tmp rm -rf ./bin
➜  /tmp go get -d github.com/koding/kite
➜  /tmp cd ./src/github.com/koding/kite
➜  kite git:(master) dep ensure
➜  kite git:(master) ✗ go run ./examples/exp2/exp2.go
2018-01-08 20:00:29 [exp2] INFO     Dialing '' kite: http://localhost:3636/kite
```

mind the `-d` in go get 
you can install the tool from [here](https://github.com/golang/dep#setup)
