### ISSUE TITLE
github.com/koding/kite/kite.go:174:22: multiple-value uuid.NewV4() in single-value context

### ISSUE THREAD

**Issue by zdywjj** [koding/kite#220]
# go get github.com/koding/kite
# github.com/koding/kite
github.com/koding/kite/kite.go:174:22: multiple-value uuid.NewV4() in single-value context

**Comment by lijasonvip** [comment]
Same problem occurs !

**Comment by wujianqiangwjq** [comment]
Same problem occurs!  go version:1.9.4
