### ISSUE TITLE
Build fails with kitekey.go:79, cannot use GetKontrolKey ...

### ISSUE THREAD

**Issue by serkanserttop** [koding/kite#87]
Pasting error from go get:
koding/kite/kitekey/kitekey.go:79: cannot use GetKontrolKey (type func(*jwt.Token) ([]byte, error)) as type jwt.Keyfunc in argument to jwt.Parse

**Comment by fatih** [comment]
Thanks for reporting, I'll look into it asap.

**Comment by fatih** [comment]
@serkanserttop I've just tried it again and it works without any problem. What exactly did you do to get that error? `go get` doesn't cause any error right now.

**Comment by serkanserttop** [comment]
I forgot to add "-u" tag, my fault.
Thanks for the help.
