### ISSUE TITLE
Generated kite.key is invalid

### ISSUE THREAD

**Issue by devinsba** [koding/kite#89]
I am trying to set up a local kontrol install and I am pretty sure I generated my keys and everything correctly but when I go to check the key that i generated with `kontrol -initial` with `kite showkey` I am getting an error of:

```
Invalid Key: Key must be PEM encoded PKCS1 or PKCS8 private key
```

**Comment by devinsba** [comment]
Looks like I had my public key in the wrong format. I ended up with a ssh format instead of the RSA block format. I will try to document how to go about setting up a kontrol server once I have it fully up and running since there is no documentation at this point

**Comment by fatih** [comment]
Yeah documentation is sparse, you are right. However if you have problems just let us know, at least I can guide you to the right file or doc, so you don't get problems :)
